/* Инициализация GPIO */
#include "GPIO.h"

void GPIO_Full_Init() {
/* --- Скорость портов --- */
WRITE_REG(GPIOA->OSPEEDR, 0xFFFFFFFF);
WRITE_REG(GPIOB->OSPEEDR, 0xFFFFFFFF);
WRITE_REG(GPIOC->OSPEEDR, 0xFFFFFFFF);

/* --------------- Аналоговые устройства --------------- */
//Joystick, Regulator, Microphone
//Режим: Analog; Подтяжка: OFF; Скорость: Средняя
//Порты (PA0, PA1), PA4, PB0

// PORT A0
MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODER0, 3 << GPIO_MODER_MODER0_Pos);
MODIFY_REG(GPIOA->PUPDR, GPIO_PUPDR_PUPD0_Msk, 0 << GPIO_PUPDR_PUPD0_Pos);
//PORT A1
MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODER1_Msk, 3 << GPIO_MODER_MODER1_Pos);
MODIFY_REG(GPIOA->PUPDR, GPIO_PUPDR_PUPD1_Msk, 0 << GPIO_PUPDR_PUPD1_Pos);
//PORT A4
MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODER4_Msk, 3 << GPIO_MODER_MODER4_Pos);
MODIFY_REG(GPIOA->PUPDR, GPIO_PUPDR_PUPD4_Msk, 0 << GPIO_PUPDR_PUPD4_Pos);
//PORT B0
MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODER0_Msk, 3 << GPIO_MODER_MODER0_Pos);
MODIFY_REG(GPIOB->PUPDR, GPIO_PUPDR_PUPD0_Msk, 0 << GPIO_PUPDR_PUPD0_Pos);

/* --------------- Шина I2C --------------- */
//Используется I2C 1. PB8: SCL PB9: SCL
//Mode: Alternate. Alternate High Register = AFRH4 (= I2C)

//PORT B8 | SCL
MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODER8_Msk, 2 << GPIO_MODER_MODER8_Pos);
MODIFY_REG(GPIOB->PUPDR, GPIO_PUPDR_PUPD8_Msk, 0 << GPIO_PUPDR_PUPD8_Pos);
MODIFY_REG(GPIOB->AFR[1], GPIO_AFRH_AFSEL8_Msk, 4 << GPIO_AFRH_AFSEL8_Pos);
//MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED8_Msk, 3 << GPIO_OSPEEDR_OSPEED8_Pos);
//PORT B9 | SDA
MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODER9_Msk, 2 << GPIO_MODER_MODER9_Pos);
MODIFY_REG(GPIOB->PUPDR, GPIO_PUPDR_PUPD9_Msk, 0 << GPIO_PUPDR_PUPD9_Pos);
MODIFY_REG(GPIOB->AFR[1], GPIO_AFRH_AFSEL9_Msk, 4 << GPIO_AFRH_AFSEL9_Pos);
//MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED9_Msk, 3 << GPIO_OSPEED_OSPEED9_Pos);

/* --------------- Шина SPI --------------- */
//Используется SPI 1. PB4: MISO PB5: MOSI PC10: SCK
//Mode: FullDuplex-Master. Alternate Low Register = AFRL6

//PORT B4 | MISO
MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODER4_Msk, 2 << GPIO_MODER_MODER4_Pos);
MODIFY_REG(GPIOB->PUPDR, GPIO_PUPDR_PUPD4_Msk, 0 << GPIO_PUPDR_PUPD4_Pos);
MODIFY_REG(GPIOB->AFR[0], GPIO_AFRL_AFSEL4_Msk, 6 << GPIO_AFRL_AFSEL4_Pos);
//PORT B5 | MOSI
MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODER5_Msk, 2 << GPIO_MODER_MODER5_Pos);
MODIFY_REG(GPIOB->PUPDR, GPIO_PUPDR_PUPD5_Msk, 0 << GPIO_PUPDR_PUPD5_Pos);
MODIFY_REG(GPIOB->AFR[0], GPIO_AFRL_AFSEL5_Msk, 6 << GPIO_AFRL_AFSEL5_Pos);
//PORT C10 | SCK
MODIFY_REG(GPIOC->MODER, GPIO_MODER_MODER10_Msk, 2 << GPIO_MODER_MODER10_Pos);
MODIFY_REG(GPIOC->PUPDR, GPIO_PUPDR_PUPD10_Msk, 0 << GPIO_PUPDR_PUPD10_Pos);
MODIFY_REG(GPIOC->AFR[1], GPIO_AFRH_AFSEL10_Msk, 6 << GPIO_AFRH_AFSEL10_Pos);
//PORT B1 | RFID SELECT
MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODER1_Msk, 1 << GPIO_MODER_MODER1_Pos);
MODIFY_REG(GPIOB->PUPDR, GPIO_PUPDR_PUPD1_Msk, 0 << GPIO_PUPDR_PUPD1_Pos);
//PORT B7 | SD SELECT
MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODER7_Msk, 1 << GPIO_MODER_MODER7_Pos);
MODIFY_REG(GPIOB->PUPDR, GPIO_PUPDR_PUPD7_Msk, 0 << GPIO_PUPDR_PUPD7_Pos);
MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED7_Msk, 0 << GPIO_OSPEEDR_OSPEED7_Pos);

/* --------------- Модули UART --------------- */
//USART1/2 Alternate Function Register = AFRL/H 7
MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODER2_Msk, 2 << GPIO_MODER_MODER2_Pos);
MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODER3_Msk, 2 << GPIO_MODER_MODER3_Pos);
MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODER9_Msk, 2 << GPIO_MODER_MODER9_Pos);
MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODER10_Msk, 2 << GPIO_MODER_MODER10_Pos);
MODIFY_REG(GPIOA->AFR[0], GPIO_AFRL_AFSEL2_Msk, 7 << GPIO_AFRL_AFSEL2_Pos);
MODIFY_REG(GPIOA->AFR[0], GPIO_AFRL_AFSEL3_Msk, 7 << GPIO_AFRL_AFSEL3_Pos);
MODIFY_REG(GPIOA->AFR[1], GPIO_AFRH_AFSEL9_Msk, 7 << GPIO_AFRH_AFSEL9_Pos);
MODIFY_REG(GPIOA->AFR[1], GPIO_AFRH_AFSEL10_Msk, 7 << GPIO_AFRH_AFSEL10_Pos);
//USART 6 Alternate Function Register = AFRH 8
MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODER11_Msk, 2 << GPIO_MODER_MODER11_Pos);
MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODER12_Msk, 2 << GPIO_MODER_MODER12_Pos);
MODIFY_REG(GPIOA->AFR[1], GPIO_AFRH_AFSEL11_Msk, 8 << GPIO_AFRH_AFSEL11_Pos);
MODIFY_REG(GPIOA->AFR[1], GPIO_AFRH_AFSEL12_Msk, 8 << GPIO_AFRH_AFSEL12_Pos);

/* --------------- DHT11 --------------- */
//PORT A15 | INPUT
MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODER15_Msk, 0 << GPIO_MODER_MODER15_Pos);
MODIFY_REG(GPIOA->OSPEEDR, GPIO_OSPEEDR_OSPEED15_Msk, 2 << GPIO_OSPEEDR_OSPEED15_Pos);

/* --------------- SERVO --------------- */
//PORT B6 | ALTERNATE FUNCTION 2 = TIMER4 CHANNEL 1
MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODER6_Msk, 2 << GPIO_MODER_MODER6_Pos);
MODIFY_REG(GPIOB->AFR[0], GPIO_AFRL_AFSEL6_Msk, 2 << GPIO_AFRL_AFSEL6_Pos);

/* --------------- SPEAKER --------------- */
//PORT B10 | ALTERNATE FUNCTION 1 = TIMER2 CHANNEL 3
MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODER10_Msk, 2 << GPIO_MODER_MODER10_Pos);
MODIFY_REG(GPIOB->AFR[1], GPIO_AFRH_AFSEL10_Msk, 1 << GPIO_AFRH_AFSEL10_Pos);

/* --------------- IR RECEIVER --------------- */
//PORT A8 | INPUT
MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODER8_Msk, 0 << GPIO_MODER_MODER8_Pos);

/* --------------- KEYBOARD --------------- */
//Используется SPI 2. PB13: SCK PB14: MISO
//Mode: HalfDuplex-Master. Alternate High Register = AFRL5 (= SPI2)
MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODER13_Msk, 2 << GPIO_MODER_MODER13_Pos);
MODIFY_REG(GPIOB->AFR[1], GPIO_AFRH_AFSEL13_Msk, 5 << GPIO_AFRH_AFSEL13_Pos);
MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODER14_Msk, 2 << GPIO_MODER_MODER14_Pos);
MODIFY_REG(GPIOB->AFR[1], GPIO_AFRH_AFSEL14_Msk, 5 << GPIO_AFRH_AFSEL14_Pos);

}
